### ISSUE TITLE
Basic Authentication throws - No Transport providers available.

### ISSUE THREAD

**Issue by rnarasim** [anaplaninc/anaplan-mulesoft#44]
Hello:
I am testing this using the demo project provided. I switched to Anaplan Basic Auth instead of certificate authentication. I get the an error "No Transport Providers Available". Here is the complete stack trace.

Any thoughts?

org.mule.api.ConnectionException: No transport providers available; check the classpath contains the necessary libraries
org.mule.api.ConnectionException: No transport providers available; check the classpath contains the necessary libraries
	at com.anaplan.connector.connection.BaseConnectionStrategy.connectToApi(BaseConnectionStrategy.java:90)
	at com.anaplan.connector.connection.BasicAuthConnectionStrategy.connect(BasicAuthConnectionStrategy.java:74)
	at com.anaplan.connector.connectivity.BasicAuthConnectionStrategyAnaplanConnectorAdapter.connect(BasicAuthConnectionStrategyAnaplanConnectorAdapter.java:21)
	at com.anaplan.connector.connectivity.BasicAuthConnectionStrategyAnaplanConnectorAdapter.connect(BasicAuthConnectionStrategyAnaplanConnectorAdapter.java:9)
	at org.mule.devkit.3.6.1.shade.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:47)
	at org.mule.devkit.3.6.1.shade.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:15)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at com.anaplan.connector.connectivity.AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.acquireConnection(AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.java:261)
	at com.anaplan.connector.connectivity.AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.test(AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.java:373)
	at org.mule.tooling.metadata.api.utils.ConnectionTester.internalTestConnection(ConnectionTester.java:84)
	at org.mule.tooling.metadata.api.utils.ConnectionTester.testConnectionFor(ConnectionTester.java:109)
	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:68)
	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:1)
	at org.mule.tooling.utils.SilentRunner.run(SilentRunner.java:25)
	at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:17)
	at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:37)
	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1.run(TestConnectorConnectionFromMuleConfigAction.java:65)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.anaplan.connector.exceptions.AnaplanConnectionException: No transport providers available; check the classpath contains the necessary libraries
	at com.anaplan.connector.connection.AnaplanConnection.cacheService(AnaplanConnection.java:242)
	at com.anaplan.connector.connection.AnaplanConnection.openConnection(AnaplanConnection.java:279)
	at com.anaplan.connector.connection.BaseConnectionStrategy.connectToApi(BaseConnectionStrategy.java:88)
	... 17 more
Caused by: com.anaplan.client.transport.AnaplanAPITransportException: No transport providers available; check the classpath contains the necessary libraries
	at com.anaplan.client.transport.TransportProviderFactory.<init>(TransportProviderFactory.java:57)
	at com.anaplan.client.transport.TransportProviderFactory.getInstance(TransportProviderFactory.java:39)
	at com.anaplan.client.Service.getTransportProvider(Service.java:239)
	at com.anaplan.client.Service.getWorkspaces(Service.java:316)
	at com.anaplan.connector.connection.AnaplanConnection.cacheService(AnaplanConnection.java:229)
	... 19 more

  java.lang.Throwable: org.mule.api.ConnectionException: No transport providers available; check the classpath contains the necessary libraries
  	at com.anaplan.connector.connection.BaseConnectionStrategy.connectToApi(BaseConnectionStrategy.java:90)
  	at com.anaplan.connector.connection.BasicAuthConnectionStrategy.connect(BasicAuthConnectionStrategy.java:74)
  	at com.anaplan.connector.connectivity.BasicAuthConnectionStrategyAnaplanConnectorAdapter.connect(BasicAuthConnectionStrategyAnaplanConnectorAdapter.java:21)
  	at com.anaplan.connector.connectivity.BasicAuthConnectionStrategyAnaplanConnectorAdapter.connect(BasicAuthConnectionStrategyAnaplanConnectorAdapter.java:9)
  	at org.mule.devkit.3.6.1.shade.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:47)
  	at org.mule.devkit.3.6.1.shade.connection.management.ConnectionManagementConnectorFactory.makeObject(ConnectionManagementConnectorFactory.java:15)
  	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
  	at com.anaplan.connector.connectivity.AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.acquireConnection(AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.java:261)
  	at com.anaplan.connector.connectivity.AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.test(AnaplanConnectorBasicAuthConnectionConnectionManagementConnectionManager.java:373)
  	at org.mule.tooling.metadata.api.utils.ConnectionTester.internalTestConnection(ConnectionTester.java:84)
  	at org.mule.tooling.metadata.api.utils.ConnectionTester.testConnectionFor(ConnectionTester.java:109)
  	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:68)
  	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:1)
  	at org.mule.tooling.utils.SilentRunner.run(SilentRunner.java:25)
  	at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:17)
  	at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:37)
  	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1.run(TestConnectorConnectionFromMuleConfigAction.java:65)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: com.anaplan.connector.exceptions.AnaplanConnectionException: No transport providers available; check the classpath contains the necessary libraries
  	at com.anaplan.connector.connection.AnaplanConnection.cacheService(AnaplanConnection.java:242)
  	at com.anaplan.connector.connection.AnaplanConnection.openConnection(AnaplanConnection.java:279)
  	at com.anaplan.connector.connection.BaseConnectionStrategy.connectToApi(BaseConnectionStrategy.java:88)
  	... 17 more
  Caused by: com.anaplan.client.transport.AnaplanAPITransportException: No transport providers available; check the classpath contains the necessary libraries
  	at com.anaplan.client.transport.TransportProviderFactory.<init>(TransportProviderFactory.java:57)
  	at com.anaplan.client.transport.TransportProviderFactory.getInstance(TransportProviderFactory.java:39)
  	at com.anaplan.client.Service.getTransportProvider(Service.java:239)
  	at com.anaplan.client.Service.getWorkspaces(Service.java:316)
  	at com.anaplan.connector.connection.AnaplanConnection.cacheService(AnaplanConnection.java:229)
  	... 19 more
  
  	at org.mule.tooling.metadata.utils.MetadataUtils.showErrorMessage(MetadataUtils.java:414)
  	at org.mule.tooling.metadata.utils.MetadataUtils.showTestConnectionErrorMessage(MetadataUtils.java:379)
  	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction.displayResultMessage(TestConnectorConnectionFromMuleConfigAction.java:110)
  	at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction.run(TestConnectorConnectionFromMuleConfigAction.java:98)
  	at org.mule.tooling.messageflow.dialog.GlobalElementDialog$1.widgetSelected(GlobalElementDialog.java:403)
  	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
  	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4042)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3669)
  	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
  	at org.eclipse.jface.window.Window.open(Window.java:808)
  	at org.mule.tooling.ui.modules.core.widgets.editors.GlobalRefEditor$1.run(GlobalRefEditor.java:487)
  	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
  	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
  	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
  	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:462)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
  	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4042)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3669)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
  	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
  	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by shuvozula** [comment]
Thanks for reporting. We're looking into this and will update as soon as we have the fix.

**Comment by shuvozula** [comment]
Just to confirm, the error trace was reported in Anypoint Studio when you tried to run the demo flow there?

**Comment by shuvozula** [comment]
Assuming you were using Anypoint Studio, did u provide values in the src/main/app/mule-app.properties file, like the Anaplan workspace ID and model ID?

**Comment by rnarasim** [comment]
Yes it was from Anypoint Studio. In the Demo - i just changed the Cert Based auth to Basic Auth. Entered the creds. For the Test Connection - not sure if WorkSpace and Module matters - i still entered those though.

**Comment by shuvozula** [comment]
We've been able to determine the issue and working on a patch. Will keep you posted as soon as it's available. Thanks for your patience.

**Comment by rnarasim** [comment]
Is this issue applicable only to basic auth?

**Comment by shuvozula** [comment]
No it seems to be affecting Certificate Auth as well. The patch will fix these issues.

**Comment by shuvozula** [comment]
Hi,
Thanks for your patience. We just published the bug-fix to the master branch in this repository and are working towards pushing these updates to Mulesoft's update site. Once its published there, you'll be able to update your connector to the latest version v1.1.2.
Thanks.

**Comment by bdmaven** [comment]
The fix has been pushed to master now marked as version 1.1.2.
